# Configuration File

# General Configuration Variables
general:
  collector:
    log:
      # Possible values for level: debug, info, warning, error, critical
      level: info
  parser:
    log:
      # Possible values for level: debug, info, warning, error, critical
      level: info
    # Number of threads for the parser
    threads: 3
    # Timeout in minutes for flow messages in the queue that were not processed and are stuck on the queue
    #timeout: 10
    # TimeZone to calculate the timeout, it is important that the timezone of the routers and the server is the same, it is
    # recommended to use UTC
    #flow_timezone: America/Denver
  db_mongo:
    log:
      # Possible values for level: debug, info, warning, error, critical
      level: info
    # Number of threads for the db_mongo to process templates
    threads_templates: 2
    # Number of threads for the db_mongo to process flows
    threads_flows: 5

# Collector Server Configuration
collector_server:
  ip: 192.168.10.103
  port: 650
  buffer: 655535

# Queue Server Configuration
queue_server:
  ip: 192.168.10.176
  port: 5672
  username: netflow
  password: netflow
  virtual_host: /

# Mongo DB Configuration
mongo_server:
  ip: 192.168.10.176
  port: 27017
  username: netflow
  password: netflow
  db: netflow