# Configuration File

# General Configuration Variables
general:

# Collector Server Configuration
collector_server:
  ip: 192.168.10.103
  port: 650
  buffer: 4096

# Queue Server Configuration
queue_server:
  ip: 192.168.10.176