# Configuration File

# General Configuration Variables
general:
  log:
    # Possible values for level: debug, info, warning, error, critical
    level: info

# Collector Server Configuration
collector_server:
  ip: 192.168.10.103
  port: 650
  buffer: 4096

# Queue Server Configuration
queue_server:
  ip: 192.168.10.176
  port: 5672
  username: netflow
  password: netflow
  virtual_host: /